# Funding options for Pinball Accuracy Memory Trainer
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# This project doesn't accept personal donations.
# Instead, please consider supporting Project Pinball - a 501(c)(3) nonprofit
# that brings the joy of pinball to children in hospitals and children's organizations.

custom:
  - https://www.projectpinball.org/donate
