coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 10%

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false
