name: Feature Request
description: Suggest a new feature or enhancement for the Pinball Accuracy Memory Trainer
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the Pinball Accuracy Memory Trainer! Please describe your feature idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I think it would be helpful if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Another approach could be...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the app does this feature relate to?
      options:
        - Training/Practice mechanics
        - Shot configuration and setup
        - Visual playfield editor
        - Feedback and scoring
        - Performance tracking
        - UI/UX improvements
        - Preset tables
        - Data import/export
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: When I'm practicing shots from Medieval Madness, I would like to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, wireframes, or examples from other apps, share them here
      placeholder: You can paste images or links here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information that might help us understand your request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked for existing similar feature requests before creating this one
          required: true
        - label: This feature aligns with the core purpose of the app (improving pinball shot accuracy recall)
          required: true
